// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG9Yj5aJ8otGsQKdM6tyw5lAGi9NlnslY',
    appId: '1:1006708688224:web:11ad5cfc2f68c68b840a05',
    messagingSenderId: '1006708688224',
    projectId: 'app-livro-250f9',
    authDomain: 'app-livro-250f9.firebaseapp.com',
    databaseURL: 'https://app-livro-250f9-default-rtdb.firebaseio.com',
    storageBucket: 'app-livro-250f9.firebasestorage.app',
    measurementId: 'G-N4C5G672HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANAhZdJMq6WKCHKS1Unj1FfOjQMC4crVc',
    appId: '1:1006708688224:android:4144d06a11ee11b5840a05',
    messagingSenderId: '1006708688224',
    projectId: 'app-livro-250f9',
    databaseURL: 'https://app-livro-250f9-default-rtdb.firebaseio.com',
    storageBucket: 'app-livro-250f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBM71FPu4u0gj3O9fshVlMu_dNPoTnEM',
    appId: '1:1006708688224:ios:05bacddf276028cd840a05',
    messagingSenderId: '1006708688224',
    projectId: 'app-livro-250f9',
    databaseURL: 'https://app-livro-250f9-default-rtdb.firebaseio.com',
    storageBucket: 'app-livro-250f9.firebasestorage.app',
    iosBundleId: 'com.example.livro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBM71FPu4u0gj3O9fshVlMu_dNPoTnEM',
    appId: '1:1006708688224:ios:05bacddf276028cd840a05',
    messagingSenderId: '1006708688224',
    projectId: 'app-livro-250f9',
    databaseURL: 'https://app-livro-250f9-default-rtdb.firebaseio.com',
    storageBucket: 'app-livro-250f9.firebasestorage.app',
    iosBundleId: 'com.example.livro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG9Yj5aJ8otGsQKdM6tyw5lAGi9NlnslY',
    appId: '1:1006708688224:web:dea8174b8888e6de840a05',
    messagingSenderId: '1006708688224',
    projectId: 'app-livro-250f9',
    authDomain: 'app-livro-250f9.firebaseapp.com',
    databaseURL: 'https://app-livro-250f9-default-rtdb.firebaseio.com',
    storageBucket: 'app-livro-250f9.firebasestorage.app',
    measurementId: 'G-KGG1GKL7VG',
  );
}
